name: ponomar
description: Orthodox Church Calendar

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.1+11

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.3.0
  shared_preferences: ^2.1.1
  auto_size_text: ^3.0.0
  easy_localization: ^3.0.0
  path: ^1.8.3
  flutter_svg: ^2.0.5
  sqflite: ^2.2.8+3
  supercharged: ^2.1.1
  json_annotation: ^4.8.1
  sprintf: ^7.0.0
  group_list_view: ^1.1.1
  jiffy: ^6.1.0
  quiver: ^3.2.1
  flutter_archive: ^5.0.0
  audioplayers: ^4.0.1
  page_view_indicators: ^2.0.0
  dots_indicator: ^2.1.0
  share_plus: ^7.0.0
  flutter_markdown: ^0.6.14
  html: ^0.15.0
  html2md: ^1.2.6
  store_redirect: ^2.0.0
  screenshot: ^2.1.0
  in_app_purchase: ^2.0.1
  rate_my_app: ^2.0.0
  launch_review: ^3.0.1
  fluttertoast: ^8.2.1
  flutter_local_notifications: ^14.0.0+2
  rxdart: ^0.27.7
  firebase_core: ^2.12.0
  firebase_analytics: ^10.4.0
  flutter_toolkit:
    path: /Users/alexey/workspace/flutter_toolkit
  flutter_native_timezone:
    git:
      url: https://github.com/pinkfish/flutter_native_timezone.git
  flutter_html_svg: ^3.0.0-beta.1
  flutter_html: ^3.0.0-beta.1
  vocsy_epub_viewer: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/newicon2.png"
  image_path_android: "assets/images/newicon.png"

flutter_native_splash:
  image: assets/images/launch_icon.png
  color: "ffffff"
  image_dark: assets/images/launch_icon2.png
  color_dark: "000000"


flutter:
  uses-material-design: true
  fonts:
    - family: Ponomar
      fonts:
        - asset: assets/fonts/PonomarUnicode.ttf

  assets:
    - assets/images/
    - assets/calendar/
    - assets/bible/
    - assets/books/
    - assets/epubs/
    - assets/saints/
    - assets/icons/
    - assets/translations/ru/
